iceburg/web/views/__init__.py
from __future__ import division

import decimal
import logging
from multiprocessing.dummy import Pool as ThreadPool

import arrow
import pandas as pd
import requests
from flask import render_template, Blueprint, jsonify, current_app, flash, session
from pandas.io.json import json_normalize

from iceburg.web.config import Config
from iceburg.web.views.travelplan import TravelPlanForm

LOGGER = logging.getLogger(__name__)

app = Blueprint('web', __name__)

CATEGORY_FRAME = pd.DataFrame(data = {
    'detail_description': ['BT',
        'Bar',
        'Booking.com',
        'Business Rates',
        'Car Servicing',
        'Cash Withdrawals',
        'Cash withdrawal',
        'Cinema',
        'Coffee',
        'Council Tax',
        'Estate Agent',
        'Filling Station',
        'Filling station',
        'Flights',
        'Florist',
        'Gas/Elec',
        'Income',
        'London arttraction',
        'Mobile',
        'Mobile phone',
        'Monthly Golf membership',
        'Monthly Netflix Membership',
        'Paid in',
        'Parking',
        'Rent',
        'Resaurant',
        'Restaurant',
        'Restaurant/Takeway',
        'Restaurants',
        'Salary',
        'Saving',
        'Savings',
        'Shopping',
        'Spa',
        'Takeaway',
        'Telephone',
        'Tickets',
        'Transfer',
        'Water'
    ],
    'custom_category': [
        'Misc',
        'Leisure and Entertainment',
        'Travel',
        'Bills',
        'Bills',
        'Misc',
        'Misc',
        'Leisure and Entertainment',
        'Leisure and Entertainment',
        'Bills',
        'Misc',
        'Transport',
        'Transport',
        'Travel',
        'Misc',
        'Bills',
        'Misc',
        'Travel',
        'Bills',
        'Bills',
        'Leisure and Entertainment',
        'Leisure and Entertainment',
        'Misc',
        'Transport',
        'Bills',
        'Leisure and Entertainment',
        'Leisure and Entertainment',
        'Leisure and Entertainment',
        'Leisure and Entertainment',
        'Misc',
        'Misc',
        'Misc',
        'Groceries and shopping',
        'Leisure and Entertainment',
        'Leisure and Entertainment',
        'Bills',
        'Leisure and Entertainment',
        'Misc',
        'Bills'
    ]
})


def trans_to_obj(item):
    return({
        'spend_type' : item['other_account']['metadata']['more_info'],
        'amount' : decimal.Decimal(item['details']['value']['amount']),
        'new_balance' : decimal.Decimal(item['details']['new_balance']['amount']),
        'detail_description' : item['details']['description'],
        'date' : item['details']['completed']
        })


@app.route('/login')
def login():
    return render_template('login.html', api_url=Config.API_URL)

@app.route('/home')
def home():
    return render_template('home.html', api_url=Config.API_URL)

g_session = None


@app.route('/')
def index():
    global g_session

    goals = {'debits': 0, 'credits': 0}

    # get the token if not in session
    if not session.get('token'):
        login_result = requests.post(
            'https://apc.openbankproject.com/my/logins/direct',
            headers={'Authorization': 'DirectLogin username="Robert.Anz.01", password="X!f98b6237", consumer_key="n4giy0finiahltld12sfaq0c3wwak5qvpccpyojt"'}
        )
        if login_result.status_code == 200:
            session['token'] = login_result.json()['token']
            print(session['token'])
        else:
            flash('Unable to get access token {}'.format(login_result.status_code))
            return render_template('index.html', api_url=Config.API_URL, transactions={}, goals=goals)

    g_session = session['token']

    # Get the customers accounts
    get_accounts_response = requests.get(
        '{}/my/accounts'.format(current_app.config['API_URL']),
        headers={'Authorization': 'DirectLogin token="{}"'.format(session['token'])}
    )

    if get_accounts_response.status_code != 200:
        flash('Bad response from get accounts {}'.format(get_accounts_response.status_code))
        return render_template('index.html', api_url=Config.API_URL, transactions={}, goals=goals)

    # Example list of accounts
    # [{
    #   "id":"42b530a5-75d0-4249-8243-7e9c5e519ed6",
    #   "label":"Robert.Anz.01 M35 11..258",
    #   "bank_id":"au.01.aum.anz",
    #   "account_routing":{
    #     "scheme":"OBP",
    #     "address":"42b530a5-75d0-4249-8243-7e9c5e519ed6"
    #   }
    # }]

    accounts = get_accounts_response.json()

    #

    # now get the transactions
    transaction_urls = ['/banks/{bank_id}/accounts/{account_id}/owner/transactions'.format(
            bank_id=account['bank_id'], account_id=account['id']
        ) for account in accounts]

    # Make the pool of workers
    # global transaction_results
    pool = ThreadPool(3)
    transaction_results = pool.imap_unordered(get_transactions, transaction_urls)

    # transaction_results = []
    # for account in accounts:
    #     get_transactions_url = '/banks/{bank_id}/accounts/{account_id}/owner/transactions'.format(
    #         bank_id=account['bank_id'], account_id=account['id']
    #     )
    #     get_transactions_response = requests.get(
    #         '{}{url}'.format(current_app.config['API_URL'], url=get_transactions_url),
    #         headers={'Authorization': 'DirectLogin token="{}"'.format(session['token'])}
    #     )
    #     if get_accounts_response.status_code != 200:
    #         flash('Unable to retrieve transactions for account {}'.format(account['id']))
    #     else:
    #         transaction_results.append(get_transactions_response.json())

    # Example transaction data
    # {
    # "transactions": [{
    #     "id": "e6077987-7935-4bc7-9eb4-dae43d146274",
    #     "this_account": {
    #         "id": "42b530a5-75d0-4249-8243-7e9c5e519ed6",
    #         "bank_routing": {
    #             "scheme": "OBP",
    #             "address": "42b530a5-75d0-4249-8243-7e9c5e519ed6"
    #         },
    #         "account_routing": {
    #             "scheme": "OBP",
    #             "address": "42b530a5-75d0-4249-8243-7e9c5e519ed6"
    #         },
    #         "holders": [{
    #             "name": "Robert.Anz.01",
    #             "is_alias": false
    #         }],
    #         "kind": "CURRENT PLUS"
    #     },
    #     "other_account": {
    #         "id": "1c7e4e0c-36e0-4cd8-92ff-f7fca7420a40",
    #         "bank_routing": {
    #             "scheme": null,
    #             "address": null
    #         },
    #         "account_routing": {
    #             "scheme": null,
    #             "address": null
    #         },
    #         "kind": null,
    #         "metadata": {
    #             "public_alias": "ALIAS_B8BD43",
    #             "private_alias": null,
    #             "more_info": "Savings",
    #             "URL": "http://www.nab.com.au",
    #             "image_URL": "https://www.carloanworld.com.au/wp-content/uploads/2013/12/nab_logo.gif",
    #             "open_corporates_URL": null,
    #             "corporate_location": null,
    #             "physical_location": null
    #         }
    #     },
    #     "details": {
    #         "type": "10219",
    #         "description": "Savings",
    #         "posted": "2015-12-30T11:02:17Z",
    #         "completed": "2015-12-30T11:02:17Z",
    #         "new_balance": {
    #             "currency": "AUD",
    #             "amount": "16560.99"
    #         },
    #         "value": {
    #             "currency": "AUD",
    #             "amount": "-408.88"
    #         }
    #     },
    #     "metadata": {
    #         "narrative": null,
    #         "comments": [],
    #         "tags": [],
    #         "images": [],
    #         "where": null
    #     }
    # }

    # aggregate the transaction history for all accounts
    transactions = []
    for transaction_result in transaction_results:
        for transaction in transaction_result['transactions']:
            transactions.append(transaction)

    transaction_list = list()
    for item in transactions:
        transaction_list.append(trans_to_obj(item))

    transactions_df = json_normalize(transaction_list)
    # at this point we have a pandas dataframe in transactions_df
    # columns:
    #   spend_type: string
    #   amount: decimal
    #   detail_description: string
    #   date: datetime
    #   new_balance: decimal

    spend_summary = transactions_df[transactions_df['amount'] < 0]\
        .groupby(['detail_description'])['amount']\
        .sum().reset_index()

    spend_summary_recoded = spend_summary.merge(CATEGORY_FRAME, how = 'left', on = 'detail_description')\
      .fillna('Misc')\
      .groupby(['custom_category'])['amount']\
      .sum()


    credits = transactions_df[transactions_df['amount'] > 0]['amount'].sum()
    debits = transactions_df[transactions_df['amount'] < 0]['amount'].sum()
    goals = {'debits': round(debits,0), 'credits': round(credits,0)}
    return render_template('index.html', api_url=Config.API_URL, transactions = spend_summary_recoded.to_dict(), goals=goals)


def get_transactions(url):
    # global transaction_results
    print('{}{url}'.format('https://apc.openbankproject.com/obp/v3.0.0', url=url))
    get_transactions_response = requests.get(
        '{}{url}'.format('https://apc.openbankproject.com/obp/v3.0.0', url=url),
        headers={'Authorization': 'DirectLogin token="{}"'.format(g_session)}
    )
    if get_transactions_response.status_code == 200:
        return get_transactions_response.json()
    else:
        return {}


@app.route('/api/holiday_cost/<destination>/<rating>/<days>', methods=['GET'])
def api_holiday_cost_get(destination, rating, days):

    holiday_destination = {
        'Australia': (180, 330, 800),
        'Austria': (160, 440, 1200),
        'Bahamas': (180, 330, 3000),
        'United Kingdom': (88, 170, 2000),

iceburg/web/views/travelplan.py
import requests
from flask import current_app
from wtforms import DecimalField, SelectField
from wtforms.validators import input_required
from flask_wtf import FlaskForm


class TravelPlanForm(FlaskForm):
    data = {}
    errors = []

    facilities = SelectField(
        'Where do you want to go?',
        coerce=int,
        description='Select the country',
    )

    def __init__(self, *args, **kwargs):
        FlaskForm.__init__(self, *args, **kwargs)
        self.facilities.choices = [(1, 'one'), (2, 'two')]

iceburg/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    {% block css %}
    {% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{url_for('web.index')}}">project iceburg</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Option 1</a></li>
                        <li><a href="#">Option 2</a></li>
                    </ul>
                </li>
                <li><a href="{{url_for('web.index')}}">Help</a></li>
            </ul>
            <!--<form class="navbar-form navbar-right">-->
                <!--<input type="text" class="form-control" placeholder="Search...">-->
            <!--</form>-->
        </div>
    </div>
</nav>


<div class="container">
    <div>
        {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{category}} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% block container %}{% endblock %}
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.js') }}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

iceburg/web/templates/home.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>IceBerg</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/font-awesome/css/font-awesome.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/Ionicons/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/AdminLTE.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/skin-black.min.css') }}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/jquery-icheck/skins/square/blue.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/animate.css/animate.min.css') }}" />

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- danger: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-black sidebar-collapse">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>I</b>B</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Ice</b>Berg </span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
    </nav>
  </header>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="row">
        

      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) 2.2.3 -->
<script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='js/app.min.js') }}"></script>

<script src="{{ url_for('static', filename='bower_components/d3/d3.min.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/d3-liquid-fill-gauge/liquidFillGauge.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/fastclick/lib/fastclick.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/jquery-smilscroll/jquery.slimscroll.min.js') }}"></script>

</body>
</html>

iceburg/web/templates/index.html
{% extends 'base.html' %}

{% block title %}Project Iceburg{% endblock %}

{% block container %}
<h1>project iceburg</h1>
<p><code>API URL={{ api_url }}</code></p>

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Transactions</h3>
            </div>
            <p>credits = {{ goals.credits }}</p>
            <p>debits = {{ goals.debits }}</p>
            <p>net = {{ goals.credits + goals.debits }}</p>
            <table class="table">
                <tr>
                    <th>Date</th>
                    <th class="text-right">Amount</th>
                </tr>
                {% for transaction in transactions %}
                <tr>
                    <td>{{ transaction }}</td>
                    <td class="text-right">{{ transactions[transaction] }}</td>
                </tr>
                {% endfor %}
            </table>

        </div>
    </div>
</div>
{% endblock %}

iceburg/web/templates/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>IceBerg| Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/font-awesome/css/font-awesome.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/Ionicons/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/AdminLTE.min.css') }}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/jquery-icheck/skins/square/blue.css') }}">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/skin-black.min.css') }}">

  <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/animate.css/animate.min.css') }}" />

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo animated slideInLeft">
    <a href="#"><b>Ice</b>Berg</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>


      <div class="form-group has-feedback">
        <input type="username" class="form-control" placeholder="Username">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <a href="#" id="signIn" class="btn btn-primary btn-block btn-flat">Sign In</a>
        </div>
        <!-- /.col -->
      </div>

<!--
    <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div>
    <!-- /.social-auth-links -->

    <a href="#">I forgot my password</a><br>
    <a href="register.html" class="text-center">Register</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- Wait modal-->
<div class="modal"><!-- Place at bottom of page --></div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) 2.2.3 -->
<script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- iCheck -->
<script src="{{ url_for('static', filename='bower_components/jquery-icheck/icheck.min.js') }}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });

    $("#signIn").click(function() {
      //authenticate and Redirect to Next page
    });

  });
</script>
</body>
</html>

iceburg/web/templates/travelplan.html
{% extends 'base.html' %}

{% block title %}Plan your travel{% endblock %}

{% macro form_field(field) -%}
<div class="form-group {% if field.errors %}has-error{% endif %}">
    {{ field.label }}
    {% if field.data %}
        {{ field(class="form-control", value=field.data) }}
    {% else %}
        {{ field(class="form-control") }}
    {% endif %}
    {% if field.errors %}
    <span class="glyphicon glyphicon-warning-sign form-control-feedback" aria-hidden="true"></span>
    <span class="help-block">{{ field.errors[0] }}</span>
    {% endif %}
    <small class="form-text text-muted">{{ field.description }}</small>
</div>
{%- endmacro %}

{% block container %}
<form method="POST" action="{{url_for('web.travel_plan')}}" class="has-feedback">
    {{ form.hidden_tag() }}
    <h1>Travel plans</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group {% if form.facilities.errors %}has-error{% endif %}">
                {{ form.facilities.label }}
                {{ form.facilities(class="form-control") }}
                <small id="facilitySelectHelp" class="form-text text-muted">{{ form.facilities.description }}</small>
            </div>
        </div>
    </div>
</form>

{% if config.DEBUG %}
<pre>{{ form.data | pprint }}</pre>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='bower_components/vue/dist/vue.js') }}"></script>
<script>
var sliders = new Vue({
  el: '#sliders',
  data: {
  }
})
</script>
{% endblock %}